name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - uses: actions/checkout@v3
      - name: golangci-lint
        # reference: https://golangci-lint.run/usage/configuration/#command-line-options
        timeout-minutes: 3
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46
          # workaround from https://github.com/golangci/golangci-lint-action/issues/119
          args: '--out-${NO_FUTURE}format=colored-line-number --timeout=1m'
